### ISSUE TITLE
Add Device

### ISSUE THREAD

**Issue by jagathkumar** [muthukumarclay/LynkTest#5]
Device item should have a default values as device name: Lynk , icon: keys, color: Brown , ringtone: rintone1, when the user force to terminate the app before giving the confirmation button.

**Comment by muthukumarclay** [comment]
- [ ] If the major and minor id already exists, do not connect.
- [ ] Let the user know that internet connection is not available and going to save the data locally. We consider this device as Temp device.
- [ ] You can delete the temp device without internet
- [ ] Once the internet is online, save the temp device to server
- [ ] Allow the user to use the device even if there is no internet in all cases like saving settings.

**Comment by jagathkumar** [comment]
App device setting page hang-up, when the user tries to delete the device, on a condition when the device, use the default setting.

**Comment by muthukumarclay** [comment]
When you delete the device, all the local data is being sent to server.
This takes some seconds and sometimes it takes even more than 30 seconds
due to slow speed of the internet. So during that time you can’t interact
with the UI so it might look like it is hanging actually it is not. Again
Everything looks banging because of the sync we do with the server. Will
add loading icon so next time you won’t get this feeling

**Comment by jagathkumar** [comment]
note its hand-up after "not able to process your request" notification.

**Comment by jagathkumar** [comment]
okay got your point.

**Comment by jagathkumar** [comment]
we can close this once the UI added.

**Comment by muthukumarclay** [comment]
I created this as a separate issue, because we need to implement this wherever we send data to server. Please refer the issue #18
